#! /usr/bin/bash
### install miniconda
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
bash ~/miniconda.sh -b -p $HOME/.local/share/miniconda3

### install zsh/fzf
$HOME/.local/share/miniconda3/bin/conda install zsh fzf -c conda-forge -y

### link zsh
mkdir ~/.local/bin
ln -s $HOME/.local/share/miniconda3/bin/zsh ~/.local/bin/zsh


